douaneintra_homepage:
    pattern:  /index
    defaults: { _controller: douaneintraBundle:Default:index }

upload:
    pattern: /docUpload
    defaults: {_controller: douaneintraBundle:Default:upload}

show:
    pattern: /docShow
    defaults: {_controller: douaneintraBundle:Default:show}

download_route:
    pattern:  /download/{id}
    defaults: { _controller: douaneintraBundle:Default:download }