parameters:
#    douaneintra.example.class: douane\intraBundle\Example

services:
#    douaneintra.example:
#        class: %douaneintra.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
